[[libidn]]
arch = "aarch64"
git-tree-sha1 = "f753dca4ca05fe62a843c519989873d0b7494038"
os = "macos"

    [[libidn.download]]
    sha256 = "ab6476a825d3a807eb205df7253b2257befb2afda7d9b85c3756dd2e97e5383d"
    url = "https://github.com/JuliaBinaryWrappers/libidn_jll.jl/releases/download/libidn-v1.43.0+0/libidn.v1.43.0.aarch64-apple-darwin.tar.gz"
[[libidn]]
arch = "aarch64"
git-tree-sha1 = "240898c5e8c1c085ea8f906eb4b0a45c25a50e0a"
libc = "glibc"
os = "linux"

    [[libidn.download]]
    sha256 = "e96d648e3392b1340f0639233fe6b83e8b6b0b6f81a4e287f48c9a9892f8d491"
    url = "https://github.com/JuliaBinaryWrappers/libidn_jll.jl/releases/download/libidn-v1.43.0+0/libidn.v1.43.0.aarch64-linux-gnu.tar.gz"
[[libidn]]
arch = "aarch64"
git-tree-sha1 = "4b6968e5aab3d6b026b0d9e373012dbe97929e34"
libc = "musl"
os = "linux"

    [[libidn.download]]
    sha256 = "e56d8c28b049c3654d37dcdc35024736491b63ac5c93b67873a1e80bd901808f"
    url = "https://github.com/JuliaBinaryWrappers/libidn_jll.jl/releases/download/libidn-v1.43.0+0/libidn.v1.43.0.aarch64-linux-musl.tar.gz"
[[libidn]]
arch = "aarch64"
git-tree-sha1 = "00589e50ecedd8d52c6547b8d22420d7e94482a3"
os = "freebsd"

    [[libidn.download]]
    sha256 = "f5139fea0c3a028fd91e1526d5c72fad87b6fc95c444ca89ddd8a1a2f8ce200d"
    url = "https://github.com/JuliaBinaryWrappers/libidn_jll.jl/releases/download/libidn-v1.43.0+0/libidn.v1.43.0.aarch64-unknown-freebsd.tar.gz"
[[libidn]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "880da509b5ee8b4cce498fdaafa74e06f6820838"
libc = "glibc"
os = "linux"

    [[libidn.download]]
    sha256 = "3883ae48ad03150f651b9b2f0f1a647732ebe56c18d87553480c8e5ed82388d8"
    url = "https://github.com/JuliaBinaryWrappers/libidn_jll.jl/releases/download/libidn-v1.43.0+0/libidn.v1.43.0.armv6l-linux-gnueabihf.tar.gz"
[[libidn]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7c795c0771c3993722f034c3daeffbdba1ba7e64"
libc = "musl"
os = "linux"

    [[libidn.download]]
    sha256 = "791882a56a7931c7cd5a768bda7c6688c33a45a5f43e2d9032d6699a3fc15277"
    url = "https://github.com/JuliaBinaryWrappers/libidn_jll.jl/releases/download/libidn-v1.43.0+0/libidn.v1.43.0.armv6l-linux-musleabihf.tar.gz"
[[libidn]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "544295bf587e108bf8ab0fe62b256a30387bd69d"
libc = "glibc"
os = "linux"

    [[libidn.download]]
    sha256 = "f289de22727a484378a0fd0e686b1e33285a3f7560d2bf7aafddacf0103106fe"
    url = "https://github.com/JuliaBinaryWrappers/libidn_jll.jl/releases/download/libidn-v1.43.0+0/libidn.v1.43.0.armv7l-linux-gnueabihf.tar.gz"
[[libidn]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3e581a7a594c92ee009fda1ab07438594208ce22"
libc = "musl"
os = "linux"

    [[libidn.download]]
    sha256 = "94f2cc5f927cc739e4a2f71629e8380dcaa9b93b9e923a0f323046f0bc2465b8"
    url = "https://github.com/JuliaBinaryWrappers/libidn_jll.jl/releases/download/libidn-v1.43.0+0/libidn.v1.43.0.armv7l-linux-musleabihf.tar.gz"
[[libidn]]
arch = "i686"
git-tree-sha1 = "b07a3d078cfdf44b8a4b38d501ff68d6a73a58b8"
libc = "glibc"
os = "linux"

    [[libidn.download]]
    sha256 = "c3cea3b194d92e067019c40af78c6b57028278aa944c3bd55328de0150f428a7"
    url = "https://github.com/JuliaBinaryWrappers/libidn_jll.jl/releases/download/libidn-v1.43.0+0/libidn.v1.43.0.i686-linux-gnu.tar.gz"
[[libidn]]
arch = "i686"
git-tree-sha1 = "5f69f203918f18a0093cc22568a8a5d736d48900"
libc = "musl"
os = "linux"

    [[libidn.download]]
    sha256 = "625bb56acdc3e48d14acb6063171bd8cf6cef1710902e3cb17cd9b93dd27bab1"
    url = "https://github.com/JuliaBinaryWrappers/libidn_jll.jl/releases/download/libidn-v1.43.0+0/libidn.v1.43.0.i686-linux-musl.tar.gz"
[[libidn]]
arch = "i686"
git-tree-sha1 = "7688fcca9891981e0da651e9bcc479d9ed6c8c86"
os = "windows"

    [[libidn.download]]
    sha256 = "27f76ec44091a4a24762fd4cee1458beffa920ae789da885ceedb918288dac01"
    url = "https://github.com/JuliaBinaryWrappers/libidn_jll.jl/releases/download/libidn-v1.43.0+0/libidn.v1.43.0.i686-w64-mingw32.tar.gz"
[[libidn]]
arch = "powerpc64le"
git-tree-sha1 = "8ecc8ef658e4a25a16678d6ea6b10974eb42d650"
libc = "glibc"
os = "linux"

    [[libidn.download]]
    sha256 = "98793159665f2f05a916e5748d43edaef20e21542cc32b998344005970f01e74"
    url = "https://github.com/JuliaBinaryWrappers/libidn_jll.jl/releases/download/libidn-v1.43.0+0/libidn.v1.43.0.powerpc64le-linux-gnu.tar.gz"
[[libidn]]
arch = "riscv64"
git-tree-sha1 = "ab5accfa6e93720a3466759e3fa78e324778e3d3"
libc = "glibc"
os = "linux"

    [[libidn.download]]
    sha256 = "94db8d33a84c1785fa5a630acc6d5f8265c6b951df0f0c9fcc9da47a41f8e0a6"
    url = "https://github.com/JuliaBinaryWrappers/libidn_jll.jl/releases/download/libidn-v1.43.0+0/libidn.v1.43.0.riscv64-linux-gnu.tar.gz"
[[libidn]]
arch = "x86_64"
git-tree-sha1 = "07bb335f86b1dcf5f0f37807dc528d243c0a3430"
os = "macos"

    [[libidn.download]]
    sha256 = "f4fb4e8141e8325b5f77d227edb98ddd78ebd830fb063bd53364b9b1242a8c92"
    url = "https://github.com/JuliaBinaryWrappers/libidn_jll.jl/releases/download/libidn-v1.43.0+0/libidn.v1.43.0.x86_64-apple-darwin.tar.gz"
[[libidn]]
arch = "x86_64"
git-tree-sha1 = "219637f9e780c5516c54f9de2990a60c8913e0b1"
libc = "glibc"
os = "linux"

    [[libidn.download]]
    sha256 = "8bfb4135d8f3487061af74cc9fb2eaa8a44aba0be2b7244c6797d3b499a9fdb7"
    url = "https://github.com/JuliaBinaryWrappers/libidn_jll.jl/releases/download/libidn-v1.43.0+0/libidn.v1.43.0.x86_64-linux-gnu.tar.gz"
[[libidn]]
arch = "x86_64"
git-tree-sha1 = "b353f39b5c3860647aed9615b491bfefbd1dba90"
libc = "musl"
os = "linux"

    [[libidn.download]]
    sha256 = "5b8778164277dd7fe10245e7e8be23f3bdc7b486c8628e6d6fc49f1fa1dc517c"
    url = "https://github.com/JuliaBinaryWrappers/libidn_jll.jl/releases/download/libidn-v1.43.0+0/libidn.v1.43.0.x86_64-linux-musl.tar.gz"
[[libidn]]
arch = "x86_64"
git-tree-sha1 = "4151370a37a0d9865749927b01fb3aa7552c4fb3"
os = "freebsd"

    [[libidn.download]]
    sha256 = "046f0a7506e731e2667e16f65866a94ab16eb87f2df9aa4423490a9b4a137fab"
    url = "https://github.com/JuliaBinaryWrappers/libidn_jll.jl/releases/download/libidn-v1.43.0+0/libidn.v1.43.0.x86_64-unknown-freebsd.tar.gz"
[[libidn]]
arch = "x86_64"
git-tree-sha1 = "a2858b00d1689ab5a1d8ba1467c346e21b075187"
os = "windows"

    [[libidn.download]]
    sha256 = "5d9235a20f11c7264b34f0c09609b416831aa49eb58a706aaede3228738854f5"
    url = "https://github.com/JuliaBinaryWrappers/libidn_jll.jl/releases/download/libidn-v1.43.0+0/libidn.v1.43.0.x86_64-w64-mingw32.tar.gz"
